apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: localhost
spec:
  acme:
    email: ${EMAIL_ADDRESS}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare
              key: api-token